package utils;

public class Locators {
	public static final String TEST_CHROME_PATH ="/Users/rchacon/Documents/RealSynch/src/chromedriver";
	public static final String RS_NAME_BOX = "//input[@name=\"email\"]";
	public static final String RS_PSW_BOX = "//input[@name=\"password\"]";
	public static final String RE_SINGIN_BTN = "//button[@type=\"submit\"]";
	public static final String DRIVER_FIREFOX_PATH = "/Users/rchacon/Documents/RealSynch/src/geckodriver";
	public static final String NEW_SYNCH_BTN = "//button[contains(text(), 'Add New Synch')]";
	public static final String VOICE_PAD_PATH = "//div[@class=\"ui-g-12\"]//*[@src=\"/images/applications/voicepad.JPG\"]";
	public static final String SALES_FORCE_APP = "//*[@id=\"root\"]/div/div[4]/div/div/div[2]/div/div[7]/div/div[2]/div[1]/div[1]/div/div/img";
	public static final String RS_NEXT_BUTTON = "//*[contains(text() , \"Next\")]";
	public static final String VC_CLIENT_FIELD = "//input[@name=\"userId\"]";
	public static final String VC_USERNAME_FIELD = "//input[@name=\"loginName\"]";
	public static final String VC_PASSWORD_FIELD = "//input[@type=\"password\"]";
	public static final String SF_USERNAME_FIELD = "//input[@name=\"loginName\"]";
	public static final String SF_PASSWORD_FIELD = "//input[@type=\"password\"]";
	public static final String SF_SECURITY_TOKEN_FIELD = "//input[@name=\"loginApiKey\"]";
	public static final String FINISH_BTN = "//button[contains(text(), \"Activate\")]";
	public static final String RS_ALL_TRANSACTIONS = "//*[@id=\"root\"]/div/div[2]/div[2]/div/div[2]/div[2]/a/button";
	public static final String REALS_REGISTRATION_LINK = "//span[contains(text(), 'Register')]";
	public static final String FORGOT_PSW_LINK = "//*[contains(text(),\"Forgot\")]";
	public static final String RS_FORGOT_PSW_BOX = "//input[@type=\"text\"]";
	public static final String RS_FORGOT_SUBMIT_BTN = "//input[@type=\"submit\"]";
	public static final String PROPERTY_BASE_APP = "//img[@src=\"/images/applications/propertybase.JPG\"]";
	public static final String SOURCE_CREDENTIALS_BUTTON =  "//button[@id=\"source-box-btn\"]";
	public static final String CLOSE_BUTTON = "//button[contains(text(), 'Close')]";
	public static final String TARGET_CREDETIALS_BUTTON = "//button[@id=\"target-box-btn\"]";
	public static final String RS_REG_FIRST_NAME = "//input[@name=\"firstName\"]";
	public static final String RS_REG_LASTNAME = "//input[@name=\"lastName\"]";
	public static final String RS_REG_EMAIL = "//input[@name=\"email\"]";
	public static final String RS_REG_PASSWORD = "//input[@name=\"password\"]";
	public static final String R_REG_CONFIRM_PASSWORD = "//input[@name=\"confirmpassword\"]";
	public static final String RS_REG_SUBMIT_BUTTON = "//button[@type=\"submit\"]";
	public static final String RS_REG_BUY_PLAN_TEAM = "//label[contains(text(), 'Team')]";
	public static final String P_BASE_USERNAME_FIELD = "//input[@name=\"username\"]";
	public static final String P_BASE_PWD_FIELD = "//input[@name=\"password\"]";
	public static final String P_BASE_CLOSE_BTN = "//button[@class=\"primary-button rs-md-font\"]";
	public static final String P_BASE_CONFIG_BTN = "//button[@type=\"button\"]";
	public static final String P_BASE_SAVE_BTN = "//button[contains(text() , \"Save\")]";
	public static final String S_FORCE_VERIFY_BTN = "//button[contains(text() , \"Verify\")]";
	public static final String RS_AVATAR_BUTTON = "//img[@class=\"avatar-img-header \"]";
	public static final String RS_LOGOUT_BTN = "//a[contains(text(), 'Log out')]";
	public static final String RS_OK_BTN = "/html/body/div[3]/div[7]/div/button";
	public static final String RS_ELIPSIS_BUTTON = "//i[@class = 'fa fa-ellipsis-h']";
	public static final String RD_DEACTIVATE_BUTTON = "//button[contains(text(), 'Deactivate')]";
	public static final String RS_YES_BUTTON = " //*[contains(text(), \"Yes\")]";
	public static final String RS_CONFIRM_BUTTON = "//*[contains (text(), 'OK')]";
	public static final String RS_ACTIVE_SYNCH = "//span[text() = 'active']";
	public static final String RS_CALENDAR_BUTTON = "//i[@class='fa fa-calendar']";
	public static final String RS_ACCOUNT_SET_BUTTON = "//*[contains(text(), \"Account Settings\")]";
	public static final String RS_PLAN_BUTTON = "//*[contains(text(), \"Plan\")]";
	public static final String RS_VISA_CARD_VALIDATOR = "//img[@src=\"/images/brand-icons/visa.png\"]";
	public static final String RS_LOW_EXEC_PLAN = "//*[@id=\"root\"]/div/div[3]/div/div/div/div[2]/div/div[2]/div/div[2]/div[1]/div/button";
	public static final String RS_PLAN_CONFIRM_BUTTON = "//button[@class=\"confirm\"]";
	public static final String RS_SUCCESS_BUTTON = "//button[@class=\"confirm\"]";
	public static final String RS_TEST_SF_CHECKBOX = "//input[@value=\"https://test.salesforce.com\"]";
	public static final String RS_ACTIVATION_BUTTON = "//*[contains(text(), 'Request a new provider')]";
	public static final String SIDX_ICON_BUTTON = "//*[@src = '/images/applications/showcaseidx.JPG']" ;
	public static final String FUB_ICON_BUTTON = "//*[@src = '/images/applications/followupboss.JPG']" ;
	public static final String FUB_CREDS_BUTTON = "//input[@name=\"loginApiKey\"]";
	public static final String SUCCESS_BUTTON_OK = "/html/body/div[3]/h2";
	public static final String INPUT_SOURCE_BUTTON = "//*[@id=\"source-box-btn\"]/span";
	public static final String INPUT_TARGET_BUTTON = "//*[@id=\"target-box-btn\"]";
	public static final String FUB_VERIFY_BUTTON = "//*[contains(text(), \"Verify\")]";
	public static final String SIDX_PENCIL_BUTTON = "//*[@id=\"source-0\"]";
	public static final CharSequence FUB_API_KEY = "3058d941b787f637417f368f0eb8d53d75c877";
	public static final String FUB_IMG = "//*[@id=\"root\"]/div/div[3]/div/div/div[2]/div/div[6]/div/div[2]/div[1]/div/div/div/img";
	public static  final String VOICE_PAD_ICON = "//*[@src='/images/applications/voicepad.JPG']";
	public static  final String SALES_FORCE_ICON = "//*[@src='/images/applications/salesforce.JPG']";
	public static  final String VOICE_PAD_ID = "//*[@name='userId']";
	public static  final CharSequence SALES_FORCE_TOKEN = "zNI1ISNV5Jx0cndV8plhuwZp";
    public static  final String TEST_URL = "//*[@value'https://test.salesforce.com']";
}